### ISSUE TITLE
Add sentence validation to Paragraph block type

### ISSUE THREAD

**Issue by basmussen** [basmussen/power-adoc-linter#28]
## Feature Request

Ich möchte im den Block Type Paragraph in der Schema YAML Datei für den Block um folgendes erweitern:

```yaml
sentence:                   # Optional: Satz-Validierung
  occurrence:
    min: 3                  # Mindestens 3 Sätze pro Paragraph
    max: 10                 # Maximal 10 Sätze pro Paragraph
    severity: warn          # Optional: Überschreibt Block-Severity
  words:                    # NUR words verfügbar für Sätze
    min: 8                  # Mindestens 8 Wörter pro Satz
    max: 25                 # Maximal 25 Wörter pro Satz
    severity:               # Optional: Überschreibt Block-Severity
```

## Beschreibung

Diese Erweiterung ermöglicht es, Paragraphen auf Satzebene zu validieren:
- **occurrence**: Definiert die minimale und maximale Anzahl von Sätzen pro Paragraph
- **words**: Definiert die minimale und maximale Anzahl von Wörtern pro Satz

## Implementierungsdetails

1. Erweiterung der \`ParagraphBlock\` Klasse um eine neue innere Klasse \`SentenceConfig\`
2. Die \`SentenceConfig\` enthält:
   - \`OccurrenceConfig\` für die Anzahl der Sätze
   - Eine innere \`WordsConfig\` Klasse für die Wortanzahl pro Satz
3. Beide Konfigurationen unterstützen die optionale Severity-Hierarchie
4. Erweiterung des \`ParagraphBlockValidator\` um Satz-Validierung
5. Aktualisierung der JSON Schema Definition für Paragraph Blocks

## Acceptance Criteria

- [ ] \`ParagraphBlock.SentenceConfig\` Klasse mit Builder implementiert
- [ ] Jackson Annotations für YAML Parsing hinzugefügt
- [ ] \`ParagraphBlockValidator\` erweitert um Satz-Validierung
- [ ] Sätze werden korrekt erkannt (Punkt, Ausrufezeichen, Fragezeichen als Satzende)
- [ ] Wörter werden korrekt gezählt (durch Whitespace getrennt)
- [ ] Severity-Hierarchie funktioniert (sentence severity > block severity)
- [ ] Unit Tests für alle neuen Funktionen
- [ ] JSON Schema für paragraph-block.yaml aktualisiert
- [ ] Beispiel in linter-config-specification.yaml hinzugefügt
