### ISSUE TITLE
Add Pass Block Type Support to Linter

### ISSUE THREAD

**Issue by basmussen** [basmussen/power-adoc-linter#37]
## Description
Add support for Pass Block type validation in the AsciiDoc linter. Pass blocks (delimited by ++++) are used for raw content passthrough (HTML, XML, SVG) and require special validation rules.

### 1. Create PassBlock Configuration Class
- Extends AbstractBlock
- Supports custom attributes: `pass-type` and `pass-reason`
- Includes type validation (html, xml, svg)
- Content validation with pattern (regex) and length
- Justification requirement

### 2. YAML Schema Definition
```yaml
pass:
  name: "Passthrough Block"
  severity: error
  occurrence:
    min: 0
    max: 1
    severity: error
  type:
    required: true
    allowed: [html, xml, svg]
    severity: error
  content:
    required: true
    maxLength: 1000
    pattern: "^<[^>]+>.*</[^>]+>$"  # Example: ensure proper HTML structure
    severity: error
  justification:
    required: true
    minLength: 20
    maxLength: 200
    severity: error
```

### 3. Implementation Tasks
- [ ] Add PASS to BlockType enum
- [ ] Create PassBlock class extending AbstractBlock
- [ ] Update BlockTypeDetector to detect "pass" context
- [ ] Create PassBlockValidator implementing BlockTypeValidator
- [ ] Register in BlockValidatorFactory
- [ ] Create pass-block-schema.yaml in resources/schemas/blocks/
- [ ] Update BlockListDeserializer
- [ ] Add comprehensive tests

### 4. Documentation Requirements
- JavaDoc must explicitly document that `pass-type` and `pass-reason` are custom attributes
- Include examples of usage in JavaDoc
- Document that these are linter-specific attributes, not native AsciiDoc

### 5. Example Usage
```asciidoc
[pass,pass-type=html,pass-reason="Custom widget for product gallery"]
++++
<div class="product-slider">
  <img src="product1.jpg" alt="Product 1">
</div>
++++
```

### 6. Content Validation
- The `content.pattern` field allows regex validation of the pass block content
- If pattern is specified, the content must match the regex pattern
- Pattern validation is part of content configuration (not a separate attribute)
- Can be used to enforce specific content structures
- Content severity can be configured separately

## Acceptance Criteria
- Pass blocks are detected with "pass" context
- Custom attributes `pass-type` and `pass-reason` are validated
- Type validation enforces allowed types (html, xml, svg)
- Content length is validated
- Content pattern (regex) validation works when configured
- Content severity is properly applied
- Justification is required and validated for length
- All tests pass
- JavaDoc clearly documents custom attributes
