### ISSUE TITLE
Add LITERAL Block Type Support to Linter

### ISSUE THREAD

**Issue by basmussen** [basmussen/power-adoc-linter#40]
## Description
Add support for LITERAL block type validation in the AsciiDoc linter. Literal blocks (delimited by ....) are used for preformatted text without syntax highlighting and require specific validation rules.

### 1. YAML Configuration Structure
```yaml
- literal:
    severity: info                   # PFLICHT: Default-Severity für den gesamten Block
    occurrence:
      min: 0
      max: 3
      # Kein severity = verwendet Block-Severity (info)
    # Literal-spezifische Attribute
    title:
      required: false
      minLength: 5
      maxLength: 50
      severity: info
    lines:
      min: 1
      max: 50                        # Nicht zu lange Literal-Blöcke
      severity: warn
    indentation:
      required: false                # Ob Einrückung geprüft werden soll
      consistent: true               # Konsistente Einrückung erforderlich
      minSpaces: 0                   # Minimale Einrückung
      maxSpaces: 8                   # Maximale Einrückung
      severity: info                 # Optional: Override
```

### 2. Implementation Tasks
- [ ] Add LITERAL to BlockType enum
- [ ] Create LiteralBlock class extending AbstractBlock
- [ ] Update BlockTypeDetector to detect "literal" context
- [ ] Create LiteralBlockValidator implementing BlockTypeValidator
- [ ] Register in BlockValidatorFactory
- [ ] Update BlockListDeserializer
- [ ] Create literal-block-schema.yaml in resources/schemas/blocks/
- [ ] Add comprehensive tests
- [ ] Update documentation

### 3. Validation Features
- **Title validation**: Optional title with length constraints (5-50 chars)
- **Lines validation**: Min/max line count (1-50 lines)
- **Indentation validation** (NEW\!): 
  - Check if indentation is required
  - Verify consistent indentation across all non-empty lines
  - Validate min/max spaces (0-8)
  - Skip empty lines in consistency check

### 4. Example Usage
```asciidoc
.Example Configuration
....
server:
  host: localhost
  port: 8080
  timeout: 30s
....
```

#### LiteralBlock Structure
- TitleConfig: required, minLength, maxLength, severity
- LinesConfig: min, max, severity
- IndentationConfig: required, consistent, minSpaces, maxSpaces, severity

#### Indentation Validation Algorithm
1. Skip empty lines
2. Count leading spaces for each non-empty line
3. Check min/max constraints
4. If consistent=true, verify all lines have same indentation
5. Report violations with appropriate severity

### 6. Test Coverage Requirements
- LiteralBlock configuration tests
- Builder pattern tests
- Indentation validation edge cases:
  - Mixed indentation levels
  - Empty lines handling
  - Tab vs spaces
  - Boundary conditions (0 spaces, max spaces)
- Severity hierarchy tests
- Integration with ConfigurationLoader

## Acceptance Criteria
- Literal blocks are detected with "literal" context
- All validation rules work as specified
- Indentation validation correctly handles edge cases
- Severity hierarchy (nested config overrides block severity)
- All tests pass
- Documentation updated
