### ISSUE TITLE
Add support for audio block type in linter

### ISSUE THREAD

**Issue by basmussen** [basmussen/power-adoc-linter#44]
Ich möchte den Block Type example im Linter unterstüzen, erstelle dafür die folgende YAML Schema für den Block:
  
AUDIO
# Für Audio-Einbindungen
```
# Syntax: audio::url[]
- audio:
    severity: info                   # PFLICHT: Default-Severity für den gesamten Block
    occurrence:
      min: 0
      max: 3
      # Kein severity = verwendet Block-Severity (info)
    # Audio-spezifische Attribute
    url:
      required: true
      pattern: "^(https?://|\\./|/).*\\.(mp3|ogg|wav|m4a)$"
      severity: error
    options:
      autoplay:
        allowed: false               # Kein Autoplay erlaubt
        severity: error
      controls:
        required: true               # Controls müssen angezeigt werden
        severity: error
      loop:
        allowed: true
        severity: info
    title:
      required: true                 # Titel/Beschreibung ist Pflicht
      minLength: 10
      maxLength: 100
      severity: warn
```
	  
bewerte das für mich und zeige mir die machbarkeit. Die Vorgabe ist exakt einzuhalten!
