### ISSUE TITLE
Fix missing block type references in section-schema.yaml

### ISSUE THREAD

**Issue by basmussen** [basmussen/power-adoc-linter#49]
## Bug Description
The schema validation fails at runtime because several block types are missing from `/src/main/resources/schemas/sections/section-schema.yaml`. This affects SIDEBAR, ADMONITION, PASS, and LITERAL blocks.

## Current Behavior
When using any of these block types in a configuration, the schema validation throws an error because the block types are not referenced in the section schema.

## Expected Behavior
All implemented block types should be properly referenced in the section schema to allow schema validation to pass.

## Root Cause
The `section-schema.yaml` file is missing the `$ref` entries for:
- SIDEBAR
- ADMONITION
- PASS
- LITERAL

## Solution
Add the missing block type references to `/src/main/resources/schemas/sections/section-schema.yaml`:

```yaml
sidebar:
  $ref: "../blocks/sidebar-block-schema.yaml"
admonition:
  $ref: "../blocks/admonition-block-schema.yaml"
pass:
  $ref: "../blocks/pass-block-schema.yaml"
literal:
  $ref: "../blocks/literal-block-schema.yaml"
```

## Additional Tasks
- [ ] Add missing block type references to section-schema.yaml
- [ ] Convert sidebar-block-schema.json to YAML format for consistency
- [ ] Add integration test to verify schema validation works for all block types
- [ ] Ensure all future block types are added to section-schema.yaml

## Impact
- **Severity**: High - Prevents usage of implemented block types
- **Components**: Schema validation, Configuration loader
- **Affected versions**: Current master branch

## Testing
After fix, verify that:
1. Schema validation passes for configurations using these block types
2. `ConfigurationLoader` can successfully load YAML files with these blocks
3. No schema validation errors occur at runtime
