### ISSUE TITLE
Feature: Error Fix Suggestions with Visual Error Highlighting

### ISSUE THREAD

**Issue by basmussen** [basmussen/power-adoc-linter#55]
# Feature: Vorschläge zur Fehlerbehebung mit visueller Fehlerdarstellung

## Übersicht

Dieses Feature würde dem Power AsciiDoc Linter die Fähigkeit geben, nicht nur Fehler zu melden, sondern auch konkrete Lösungsvorschläge mit visueller Hervorhebung der Problemstellen anzubieten.

### Darstellungsprinzipien
- **2-4 Zeilen Kontext** um die Fehlerstelle
- **Fehlende Werte** mit Platzhaltern anzeigen: `«value»`
- **Falsche Werte** mit Unterstreichung markieren: `~~~~~`
- **Visuelle Hierarchie** für schnelle Erfassung

## Platzhalter-Varianten (Brainstorming)

1. **`<value>`** - Klassisch, klar als Platzhalter erkennbar
2. **`{value}`** - An Template-Syntax angelehnt
3. **`[value]`** - Eckige Klammern, deutet auf "einzufügen" hin
4. **`⟨value⟩`** - Unicode-Klammern, visuell auffällig
5. **`«value»`** - Guillemets, elegant (EMPFOHLEN)
6. **`▪value▪`** - Mit Symbolen abgegrenzt
7. **`_value_`** - Underscores, schlicht aber effektiv

### 1. Fehlender Titel
```
ERROR: Section 'introduction' is missing required title [block.section.title.missing]
  File: guide.adoc:15:1
  
  14  < /dev/null |  Some content before...
  15 | == «title»
  16 | This section needs a title but has none.
  
  💡 Suggested fix: == Introduction
```

### 2. Fehlende Attribute
```
ERROR: Listing block missing required language attribute [block.listing.language.required]
  File: examples.adoc:25:1
  
  24 | Example code:
  25 | [source,«language»]
  26 | ----
  27 | public class Example {
  
  💡 Suggested fix: [source,java]
```

### 3. Mehrere fehlende Werte
```
ERROR: Image block missing required attributes [block.image.attributes.missing]
  File: manual.adoc:88:1
  
  87 | See the diagram below:
  88 | image::«url»[alt=«description»,width=«size»]
  89 | 
  
  💡 Suggested fix: image::diagram.png[alt="System Architecture",width=600]
```

### 4. Falsches Pattern mit Unterstreichung
```
ERROR: Author must start with uppercase letter [metadata.author.pattern]
  File: README.adoc:2:9
  
   1 | = User Guide
   2 | :author: john doe
            ~~~~~~~~
   3 | :email: john@example.com
  
  💡 Suggested fix: :author: John Doe
```

### 5. Wert zu lang
```
WARN: Section title exceeds 80 characters [section.title.maxLength]
  File: tutorial.adoc:34:4
  
  33 | 
  34 | === This is an extremely long section title that contains way too many characters and should be shortened
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  35 | 
  
  💡 Suggested fix: Split into title and subtitle or shorten to:
  === Configuration Guide for Advanced Users
```

### 6. Fehlende Tabellen-Header
```
ERROR: Table missing header row [block.table.header.required]
  File: data.adoc:30-33
  
  29 | .User Data
  30 | |===
  31 | «header row»
  32 | | John | Doe | john@example.com
  33 | | Jane | Smith | jane@example.com
  
  💡 Suggested fix:
  |===
  | First Name | Last Name | Email
  
  | John | Doe | john@example.com
```

### 7. Ungültiger Enum-Wert
```
ERROR: Invalid admonition type 'HINT' [block.admonition.type.invalid]
  File: guide.adoc:67:1
  
  66 | Important information:
  67 | [HINT]
       ~~~~
  68 | ====
  69 | Remember to save your work
  
  💡 Valid types: NOTE, TIP, IMPORTANT, WARNING, CAUTION
  Suggested fix: [TIP]
```

### 8. Bereichsverletzung (Min/Max)
```
ERROR: List must have 2-5 items, found 1 [block.list.items.range]
  File: steps.adoc:44-45
  
  43 | Follow these steps:
  44 | . First step
       ┌─ ⚠️ Need at least 2 items
  45 | «add more items»
  46 | 
  
  💡 Suggested fix: Add at least one more item:
  . First step
  . Second step
```

### 9. Komplexer Fehler mit mehreren Problemen
```
ERROR: Multiple validation failures in listing block [block.listing.multiple]
  File: code.adoc:101-106
  
  100 | Here's the implementation:
  101 | [source,«language»]
  102 | .
           ~ Title too short (min: 3 chars)
  103 | ----
  104 | // Code content...
  ...|    [...98 more lines...]
      └─ ⚠️ Block too long: 102 lines (max: 50)
  
  💡 Suggested fixes:
  1. Add language: [source,java]
  2. Add title: .Example Implementation
  3. Split into smaller blocks or use includes
```

### 10. Multiple Lösungsoptionen
```
ERROR: Image URL must match pattern '.*\.(png|jpg|jpeg|svg)$' [block.image.url.pattern]
  File: tutorial.adoc:42:1
  Actual: "screenshot.PDF"
  Expected: File extension png, jpg, jpeg, or svg
  
  💡 Suggested fixes:
  
  Option 1: Change file extension (if file exists in other format)
  - image::screenshot.png[]
  - image::screenshot.jpg[]
  
  Option 2: Convert your PDF to supported format
  $ convert screenshot.PDF screenshot.png
  
  Option 3: Use pass-through block for PDF embedding
  ++++
  <object data="screenshot.PDF" type="application/pdf" width="100%" height="600px">
  ++++
```

### 1. Smart Placeholders mit Kontext-Hinweisen
```
ERROR: Image missing required attributes [block.image.attributes.missing]
  File: tutorial.adoc:78:1
  
  77 | The architecture looks like this:
  78 | image::«path/to/image.png»[alt=«meaningful description»]
                                     └─ for accessibility
  79 | 
  
  💡 Common patterns:
  - image::images/screenshot.png[alt="Application main screen"]
  - image::diagrams/architecture.svg[alt="System architecture",width=800]
```

### 2. Verschachtelte Platzhalter
```
  88 | image::«path/to/image.«ext»»[alt=«description»,width=«100-800»]
                            └─ png|jpg|svg              └─ pixels
```

### 3. Mehrfach-Werte
```
  67 | [«NOTE|TIP|IMPORTANT|WARNING|CAUTION»]
         └─ Choose one of these values
```

## Konfiguration (YAML)

```yaml
linter:
  output:
    # Anzahl der Kontext-Zeilen vor/nach dem Fehler
    context-lines: 2  # default: 2, range: 0-5
    
    # Art der Hervorhebung
    highlight-style: underline  # options: underline, box, arrow, bracket
    
    # Farbausgabe aktivieren/deaktivieren
    colors: true  # ANSI color codes für Terminal
    
    # Vorschläge anzeigen
    show-suggestions: true
    
    # Kompakt-Modus für CI/CD
    compact-mode: false  # Reduzierte Ausgabe ohne Kontext
    
    # Platzhalter-Stil
    placeholder-style: guillemets  # options: angle, curly, square, guillemets, underscore
    
    # Erweiterte Optionen
    advanced:
      # Zeige Zeilennummern
      show-line-numbers: true
      
      # Maximale Breite für Fehlerunterstreichung
      max-underline-width: 120
      
      # Zeige Regel-ID
      show-rule-id: true
      
      # Gruppiere ähnliche Fehler
      group-similar-errors: true
      
      # Zeige Fehler-Statistik am Ende
      show-summary: true
      
    # Fix-Vorschläge
    suggestions:
      # Zeige Auto-Fix Hinweis
      show-auto-fix-hint: true
      
      # Maximale Anzahl Vorschläge pro Fehler
      max-suggestions: 3
      
      # Zeige Beispiele
      show-examples: true
      
      # Zeige Links zu Dokumentation
      show-doc-links: true
```

## Auto-Fix Modus (Interaktiv)

```bash
# Interaktiv
$ power-adoc-linter --fix-interactive guide.adoc

Found 5 issues (3 auto-fixable)

[1/3] Missing section title at line 15
Suggested: == Introduction
Apply this fix? [Y/n/e(dit)]: y
✓ Fixed

[2/3] Invalid image format at line 42
Suggested: Change 'screenshot.PDF' to 'screenshot.png'
Apply this fix? [Y/n/e(dit)]: e
Enter your fix: screenshot.jpg
✓ Fixed with custom value
```

### Standard-Modus
```
ERROR: Section 'introduction' is missing required title [block.section.title.missing]
  File: guide.adoc:15:1
  
  14 | Some content before...
  15 | == «title»
  16 | This section needs a title but has none.
  
  💡 Suggested fix: == Introduction
```

### Kompakt-Modus (CI/CD)
```
guide.adoc:15:1: ERROR: Missing section title [block.section.title.missing]
  == «title» → == Introduction
```

### Gruppierte Fehler
```
Found 5 similar errors: Missing language attribute in listing blocks

  examples.adoc:25:1   [source,«language»]
  examples.adoc:67:1   [source,«language»]
  examples.adoc:102:1  [source,«language»]
  tutorial.adoc:45:1   [source,«language»]
  tutorial.adoc:89:1   [source,«language»]

💡 Common fix: Add language attribute (e.g., java, python, yaml)
🔧 Auto-fixable: Use --fix to add 'java' to all blocks
```

## Fehler-Zusammenfassung

```
═══════════════════════════════════════════════════════════════
                    Validation Summary
═══════════════════════════════════════════════════════════════
  Total files scanned:     12
  Files with errors:        4
  
  Errors:   8  ████████ 
  Warnings: 15 ███████████████
  Info:     3  ███
  
  Most common issues:
  1. Missing language attribute (5 occurrences)
  2. Section title too long (3 occurrences)  
  3. Missing image alt text (3 occurrences)
  
  💡 5 errors are auto-fixable. Run with --fix
═══════════════════════════════════════════════════════════════
```

### Fix-Provider-System
```java
public interface FixProvider {
    List<Fix> getSuggestedFixes(ValidationMessage message, BlockContext context);
}

public class Fix {
    private String description;
    private String explanation;
    private List<String> codeSnippets;
    private FixConfidence confidence; // HIGH, MEDIUM, LOW
    private boolean isAutomatable;
}
```

### Platzhalter-Formatter
```java
public class PlaceholderFormatter {
    private static final String PLACEHOLDER_START = "«";
    private static final String PLACEHOLDER_END = "»";
    
    public String format(String value) {
        return PLACEHOLDER_START + value + PLACEHOLDER_END;
    }
    
    public String formatOptional(String value) {
        return PLACEHOLDER_START + value + " (optional)" + PLACEHOLDER_END;
    }
    
    public String formatWithHint(String value, String hint) {
        return PLACEHOLDER_START + value + PLACEHOLDER_END + " ← " + hint;
    }
}
```

## Erwartete Benutzerreaktion

Benutzer würden erwarten:
1. **Sofort verständliche Lösungen** ohne Rätseln
2. **Kontext-sensitive Vorschläge** die zum Projekt passen
3. **Lerneffekt** - verstehen warum etwas falsch ist
4. **Zeitersparnis** durch Auto-Fix wo sinnvoll
5. **Kontrolle** über angewendete Änderungen

Das Feature sollte sich anfühlen wie ein **hilfreicher Kollege**, der:
- Konkrete Vorschläge macht
- Erklärt warum etwas besser ist
- Aber nie bevormundet

### Farbcodierung im Terminal
- 🔴 Problem (rot)
- 💡 Lösung (gelb)  
- ✅ Angewendet (grün)
- ℹ️ Information (blau)

### Fix-Komplexitäts-Indikator
```
🟢 Simple fix (1 line change)
🟡 Moderate fix (structural change needed)
🔴 Complex fix (requires refactoring)
```

### Diff-Vorschau
```
Preview of changes:
  
  15  - == 
  15  + == Introduction
  
  42  - image::screenshot.PDF[]
  42  + image::screenshot.png[]
  
Apply all changes? [Y/n]: 
```

## Vorteile dieser Implementierung

1. **Schnelle visuelle Erfassung** - Man sieht sofort wo das Problem liegt
2. **Kontext bleibt erhalten** - Umgebende Zeilen helfen beim Verständnis  
3. **Klare Markierung** - Unterstriche zeigen exakt die problematische Stelle
4. **Platzsparend** - Max 4 Zeilen + Markierung + Vorschlag
5. **Copy-Paste-freundlich** - Zeilennummern am Rand stören nicht
6. **Ästhetisch ansprechend** - Guillemets wirken professionell

## Acceptance Criteria

- [ ] Visuelle Fehlerdarstellung mit 2-4 Zeilen Kontext
- [ ] Platzhalter für fehlende Werte mit «» Notation
- [ ] Unterstreichung für falsche Werte
- [ ] Konkrete, copy-paste-fähige Lösungsvorschläge
- [ ] Multiple Lösungsoptionen bei Mehrdeutigkeiten
- [ ] Konfigurierbare Ausgabe via YAML
- [ ] Auto-Fix Modus (optional)
- [ ] Gruppierung ähnlicher Fehler
- [ ] Fehler-Zusammenfassung
- [ ] Farbcodierung im Terminal (optional)
- [ ] CI/CD-freundlicher Kompakt-Modus
